<#
.SYNOPSIS
    Compiles Composite.hlsl with fxc and regenerates CompositeShaders.g.cs beside it.

.DESCRIPTION
    The shim ships precompiled bytecode rather than compiling at run time, so this runs by hand
    whenever Composite.hlsl changes - not as part of the build. That keeps the Windows SDK out of the
    build's requirements and keeps the bytes that end up inside a game reviewable in a diff.

    The generated file records a SHA-256 of the HLSL, with line endings normalised to LF so a
    checkout's autocrlf setting cannot change it. SRTOverlay.Tests recomputes that hash, so editing
    the shader without rerunning this script fails a test instead of shipping stale bytecode.

.PARAMETER Fxc
    Path to fxc.exe. Defaults to the newest x64 fxc in the installed Windows 10/11 SDKs.
#>
[CmdletBinding()]
param(
    [string] $Fxc
)

$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot 'Composite.hlsl'
$output = Join-Path $PSScriptRoot 'CompositeShaders.g.cs'

if (-not $Fxc) {
    $Fxc = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin\*\x64\fxc.exe' -ErrorAction SilentlyContinue |
        Sort-Object { [version] $_.Directory.Parent.Name } |
        Select-Object -Last 1 -ExpandProperty FullName
}

if (-not $Fxc -or -not (Test-Path $Fxc)) {
    throw 'fxc.exe was not found. Install the Windows SDK or pass -Fxc.'
}

$sdkVersion = Split-Path (Split-Path (Split-Path $Fxc -Parent) -Parent) -Leaf
$scratch = New-Item -ItemType Directory -Path (Join-Path ([IO.Path]::GetTempPath()) "SRTOverlayShaders-$([Guid]::NewGuid())")

function Invoke-Fxc([string] $ShaderProfile, [string] $EntryPoint) {
    $compiled = Join-Path $scratch "$EntryPoint.cso"

    # Shader model 5.0 DXBC: accepted by every D3D12 driver, and nothing here needs 5.1 or DXIL.
    # Debug and private data are stripped; reflection is kept because it costs a few hundred bytes
    # and makes the bytecode self-describing to anyone inspecting it.
    & $Fxc /nologo /T $ShaderProfile /E $EntryPoint /O3 /Qstrip_debug /Qstrip_priv /Fo $compiled $source | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "fxc failed to compile $EntryPoint."
    }

    return [IO.File]::ReadAllBytes($compiled)
}

function Format-Bytes([byte[]] $Bytes) {
    $lines = for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $row = $Bytes[$i..([Math]::Min($i + 15, $Bytes.Length - 1))] | ForEach-Object { '0x{0:X2}' -f $_ }
        '        ' + ($row -join ', ') + ','
    }
    return $lines -join "`n"
}

try {
    $vertex = Invoke-Fxc 'vs_5_0' 'VSMain'
    $pixel = Invoke-Fxc 'ps_5_0' 'PSMain'
}
finally {
    Remove-Item $scratch -Recurse -Force
}

$normalised = ([IO.File]::ReadAllText($source)) -replace "`r`n", "`n"
$hash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($normalised)))

$generated = @"
// <auto-generated>
//     Generated by Shaders/Compile-Shaders.ps1 from Shaders/Composite.hlsl, using fxc from Windows SDK
//     $sdkVersion. Do not edit by hand: change the HLSL and rerun the script.
// </auto-generated>

namespace SRTOverlay.DirectX12;

/// <summary>Precompiled bytecode for the composite quad. See <c>Shaders/Composite.hlsl</c>.</summary>
internal static class CompositeShaders
{
    /// <summary>SHA-256 of <c>Composite.hlsl</c>, line endings normalised to LF, at generation time.</summary>
    internal const string SourceSha256 = "$hash";

    /// <summary><c>VSMain</c>, shader model 5.0.</summary>
    internal static ReadOnlySpan<byte> VertexShader =>
    [
$(Format-Bytes $vertex)
    ];

    /// <summary><c>PSMain</c>, shader model 5.0.</summary>
    internal static ReadOnlySpan<byte> PixelShader =>
    [
$(Format-Bytes $pixel)
    ];
}
"@

[IO.File]::WriteAllText($output, ($generated -replace "`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $output ($($vertex.Length) + $($pixel.Length) bytes of bytecode, source $hash)."
