<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Platforms>x86;x64</Platforms>
		<Authors>SpeedRunTool</Authors>
		<Company>$(Authors)</Company>
		<CopyrightYear>$([System.DateTime]::UtcNow.ToString("yyyy"))</CopyrightYear>
		<Copyright>Copyright © $(CopyrightYear) $(Company)</Copyright>
		<RepositoryUrl>https://github.com/$(Company)/SRTHost</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<DebugType>portable</DebugType>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<PublishProtocol>FileSystem</PublishProtocol>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>bin\$(Configuration)\$(Platform)\$(TargetFramework)</OutputPath>
		<PublishDir>bin\$(Configuration)\$(Platform)\$(TargetFramework)\publish\</PublishDir>
		<DefineConstants>$(DefineConstants);$(Platform)</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>